"""add_missing_indexes

Revision ID: 2e0e9639ac12
Revises: ece6eaedeaec
Create Date: 2026-05-22 12:29:18.214503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e0e9639ac12'
down_revision: Union[str, Sequence[str], None] = 'ece6eaedeaec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_bt_run_id', 'backtest_trades', ['run_id'], unique=False)
    op.create_index('ix_bt_run_id_exit_reason', 'backtest_trades', ['run_id', 'exit_reason'], unique=False)
    op.create_index('ix_pe_run_id', 'pipeline_errors', ['run_id'], unique=False)
    
    # These might already exist from previous failed attempts but weren't recorded in alembic_version
    # We'll use try/except or just omit them if we know they exist
    # Based on our check: ix_ts_timeframe_date and ix_ts_symbol_timeframe_date EXIST.
    # ix_ts_screener_core does NOT exist.
    
    op.create_index('ix_ts_screener_core', 'technical_signals', ['timeframe', 'date', 'above_200ema', 'is_bullish'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ts_screener_core', table_name='technical_signals')
    op.drop_index('ix_ts_symbol_timeframe_date', table_name='technical_signals')
    op.drop_index('ix_ts_timeframe_date', table_name='technical_signals')

    op.drop_index('ix_pe_run_id', table_name='pipeline_errors')
    op.drop_index('ix_bt_run_id_exit_reason', table_name='backtest_trades')
    op.drop_index('ix_bt_run_id', table_name='backtest_trades')
    # ### end Alembic commands ###
