"""add_total_symbols_to_pipeline_run

Revision ID: 3a0ddb4b9c6d
Revises: 0f1bf3f8a5ca
Create Date: 2026-05-12 12:15:52.977844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a0ddb4b9c6d'
down_revision: Union[str, Sequence[str], None] = '0f1bf3f8a5ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_runs', sa.Column('total_symbols', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_runs', 'total_symbols')
    # ### end Alembic commands ###
