"""add strategy tags to paper positions

Revision ID: 4205d5b4a8d2
Revises: c918d2a71c95
Create Date: 2026-05-31 14:38:06.808532

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4205d5b4a8d2"
down_revision: Union[str, Sequence[str], None] = "c918d2a71c95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "paper_positions",
        sa.Column(
            "strategy_tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("paper_positions", "strategy_tags")
    # ### end Alembic commands ###
