"""paper_v2 daily_snapshot + parity_check (v3/11 viz)

Revision ID: 5d30f4bfa74d
Revises: b7c4f1a2d3e8
Create Date: 2026-06-23 11:44:07.879393

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d30f4bfa74d"
down_revision: Union[str, Sequence[str], None] = "b7c4f1a2d3e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "paper_v2_daily_snapshot",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("equity", sa.Float(), nullable=False),
        sa.Column("cash", sa.Float(), nullable=False),
        sa.Column("invested_value", sa.Float(), nullable=False),
        sa.Column("exposure", sa.Float(), nullable=False),
        sa.Column("n_positions", sa.Integer(), nullable=False),
        sa.Column("index_level", sa.Float(), nullable=True),
        sa.Column("is_forward", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["paper_v2_portfolio.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "portfolio_id", "date", name="uq_paper_v2_snap_portfolio_date"
        ),
    )
    op.create_index(
        "ix_paper_v2_snap_portfolio_date",
        "paper_v2_daily_snapshot",
        ["portfolio_id", "date"],
        unique=False,
    )
    op.create_table(
        "paper_v2_parity_check",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("max_dev_bps", sa.Float(), nullable=False),
        sa.Column("tol_bps", sa.Float(), nullable=False),
        sa.Column("breaches", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["paper_v2_portfolio.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "portfolio_id", "as_of", name="uq_paper_v2_parity_portfolio_asof"
        ),
    )
    op.create_index(
        "ix_paper_v2_parity_portfolio_asof",
        "paper_v2_parity_check",
        ["portfolio_id", "as_of"],
        unique=False,
    )
    # NOTE: autogenerate also surfaced pre-existing model⇄DB drift unrelated to this
    # change (an `ix_sr_slug_date` drop on screen_results + a technical_signals.id
    # server_default alter). Those are intentionally NOT included here — this migration
    # is scoped to the two new v3/11 viz tables only (Rule 3: surgical changes).
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_paper_v2_parity_portfolio_asof", table_name="paper_v2_parity_check"
    )
    op.drop_table("paper_v2_parity_check")
    op.drop_index(
        "ix_paper_v2_snap_portfolio_date", table_name="paper_v2_daily_snapshot"
    )
    op.drop_table("paper_v2_daily_snapshot")
    # ### end Alembic commands ###
