"""enrich_backtest_models

Revision ID: 688f08625149
Revises: 1914b72f41e1
Create Date: 2026-06-07 15:38:51.052364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '688f08625149'
down_revision: Union[str, Sequence[str], None] = '1914b72f41e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_runs', sa.Column('regime_map_json', sa.Text(), nullable=True))
    op.add_column('backtest_trades', sa.Column('regime_at_signal', sa.Integer(), nullable=True))
    op.add_column('backtest_trades', sa.Column('regime_at_entry', sa.Integer(), nullable=True))
    op.add_column('backtest_trades', sa.Column('regime_at_exit', sa.Integer(), nullable=True))
    op.add_column('backtest_trades', sa.Column('market_breadth_at_entry', sa.Float(), nullable=True))
    op.add_column('backtest_trades', sa.Column('consolidation_bars_at_signal', sa.Integer(), nullable=True))
    op.add_column('backtest_trades', sa.Column('pullback_depth_pct', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtest_trades', 'pullback_depth_pct')
    op.drop_column('backtest_trades', 'consolidation_bars_at_signal')
    op.drop_column('backtest_trades', 'market_breadth_at_entry')
    op.drop_column('backtest_trades', 'regime_at_exit')
    op.drop_column('backtest_trades', 'regime_at_entry')
    op.drop_column('backtest_trades', 'regime_at_signal')
    op.drop_column('backtest_runs', 'regime_map_json')
    # ### end Alembic commands ###
