"""add_pipeline_checkpoints_and_errors

Revision ID: 780337900565
Revises: bc07cf8aa2f9
Create Date: 2026-05-11 13:55:02.495780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '780337900565'
down_revision: Union[str, Sequence[str], None] = 'bc07cf8aa2f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_checkpoints',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('completed_symbols', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.run_id'], ),
    sa.PrimaryKeyConstraint('run_id', 'phase')
    )
    op.create_table('pipeline_errors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=True),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('error_type', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_errors')
    op.drop_table('pipeline_checkpoints')
    # ### end Alembic commands ###
