"""add_technical_signal_indexes

Revision ID: 96609b572ba1
Revises: ece6eaedeaec
Create Date: 2026-05-20 17:57:21.580970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96609b572ba1'
down_revision: Union[str, Sequence[str], None] = 'ece6eaedeaec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_ts_above_200ema', 'technical_signals', ['above_200ema'], unique=False)
    op.create_index('ix_ts_rs_score', 'technical_signals', ['rs_score'], unique=False)
    op.create_index('ix_ts_symbol_timeframe_date', 'technical_signals', ['symbol', 'timeframe', 'date'], unique=False)
    op.create_index('ix_ts_timeframe_date', 'technical_signals', ['timeframe', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ts_timeframe_date', table_name='technical_signals')
    op.drop_index('ix_ts_symbol_timeframe_date', table_name='technical_signals')
    op.drop_index('ix_ts_rs_score', table_name='technical_signals')
    op.drop_index('ix_ts_above_200ema', table_name='technical_signals')
    # ### end Alembic commands ###
