"""add watchlist table

Revision ID: aaf42b552175
Revises: a36b9de49fa6
Create Date: 2026-05-24 16:15:07.722107

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aaf42b552175"
down_revision: Union[str, Sequence[str], None] = "a36b9de49fa6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "watchlist",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("added_date", sa.Date(), nullable=False),
        sa.Column("signal_date", sa.Date(), nullable=False),
        sa.Column("alert_type", sa.String(), nullable=True),
        sa.Column("quality_tier", sa.String(length=1), nullable=True),
        sa.Column("signal_score", sa.Float(), nullable=True),
        sa.Column("planned_entry_low", sa.Float(), nullable=True),
        sa.Column("planned_entry_high", sa.Float(), nullable=True),
        sa.Column("stop_loss", sa.Float(), nullable=True),
        sa.Column("target", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["symbol"],
            ["stocks.symbol"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("symbol", "signal_date"),
    )
    op.create_index("ix_watchlist_status", "watchlist", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_watchlist_status", table_name="watchlist")
    op.drop_table("watchlist")
    # ### end Alembic commands ###
