"""add_is_consolidating_to_technical_signal

Revision ID: ad73737a882d
Revises: 2e0e9639ac12
Create Date: 2026-05-22 15:28:23.019938

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ad73737a882d"
down_revision: Union[str, Sequence[str], None] = "2e0e9639ac12"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "paper_portfolio",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("starting_capital", sa.Float(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "paper_positions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("sector", sa.String(), nullable=True),
        sa.Column("signal_date", sa.Date(), nullable=False),
        sa.Column("signal_score", sa.Float(), nullable=True),
        sa.Column("ema_signal", sa.String(), nullable=True),
        sa.Column("atr_at_signal", sa.Float(), nullable=True),
        sa.Column("ema20_at_signal", sa.Float(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("wait_days_elapsed", sa.Integer(), nullable=True),
        sa.Column("pending_highest_closeness_pct", sa.Float(), nullable=True),
        sa.Column("is_invalidated", sa.Boolean(), nullable=True),
        sa.Column("entry_date", sa.Date(), nullable=True),
        sa.Column("entry_price", sa.Float(), nullable=True),
        sa.Column("entry_type", sa.String(), nullable=True),
        sa.Column("position_size", sa.Float(), nullable=True),
        sa.Column("shares", sa.Float(), nullable=True),
        sa.Column("stop_loss_price", sa.Float(), nullable=True),
        sa.Column("target_price", sa.Float(), nullable=True),
        sa.Column("highest_price", sa.Float(), nullable=True),
        sa.Column("atr_trail_active", sa.Boolean(), nullable=True),
        sa.Column("opened_at", sa.DateTime(), nullable=True),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("exit_reason", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["paper_portfolio.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_pp_portfolio_status",
        "paper_positions",
        ["portfolio_id", "status"],
        unique=False,
    )
    op.create_index("ix_pp_symbol", "paper_positions", ["symbol"], unique=False)
    op.create_table(
        "paper_trades",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("sector", sa.String(), nullable=True),
        sa.Column("signal_date", sa.Date(), nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("exit_date", sa.Date(), nullable=False),
        sa.Column("entry_price", sa.Float(), nullable=False),
        sa.Column("exit_price", sa.Float(), nullable=False),
        sa.Column("shares", sa.Float(), nullable=False),
        sa.Column("position_size", sa.Float(), nullable=False),
        sa.Column("return_pct", sa.Float(), nullable=False),
        sa.Column("pnl", sa.Float(), nullable=False),
        sa.Column("exit_reason", sa.String(), nullable=False),
        sa.Column("signal_score", sa.Float(), nullable=True),
        sa.Column("ema_signal", sa.String(), nullable=True),
        sa.Column("holding_days", sa.Integer(), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["paper_portfolio.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_pt_portfolio_id", "paper_trades", ["portfolio_id"], unique=False
    )
    op.add_column(
        "technical_signals", sa.Column("is_consolidating", sa.Boolean(), nullable=True)
    )
    op.drop_index("ix_ts_above_200ema", table_name="technical_signals")
    op.drop_index("ix_ts_rs_score", table_name="technical_signals")
    op.drop_index("ix_ts_screener_core", table_name="technical_signals")
    op.create_index(
        "ix_ts_screener_core",
        "technical_signals",
        ["timeframe", "date", "above_200ema", "is_bullish", "is_consolidating"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ts_screener_core", table_name="technical_signals")
    op.create_index(
        "ix_ts_screener_core",
        "technical_signals",
        ["timeframe", "date", "above_200ema", "is_bullish"],
        unique=False,
    )
    op.create_index("ix_ts_rs_score", "technical_signals", ["rs_score"], unique=False)
    op.create_index(
        "ix_ts_above_200ema", "technical_signals", ["above_200ema"], unique=False
    )
    op.drop_column("technical_signals", "is_consolidating")
    op.drop_index("ix_pt_portfolio_id", table_name="paper_trades")
    op.drop_table("paper_trades")
    op.drop_index("ix_pp_symbol", table_name="paper_positions")
    op.drop_index("ix_pp_portfolio_status", table_name="paper_positions")
    op.drop_table("paper_positions")
    op.drop_table("paper_portfolio")
    # ### end Alembic commands ###
