"""add_capital_and_position_size_to_backtest_run

Revision ID: b171d59174c9
Revises: b765d7520169
Create Date: 2026-05-13 13:56:22.699821

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b171d59174c9"
down_revision: Union[str, Sequence[str], None] = "b765d7520169"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "backtest_runs", sa.Column("starting_capital", sa.Float(), nullable=True)
    )
    op.add_column(
        "backtest_runs", sa.Column("position_size", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("backtest_runs", "position_size")
    op.drop_column("backtest_runs", "starting_capital")
    # ### end Alembic commands ###
