"""add_backtest_models

Revision ID: b765d7520169
Revises: 3a0ddb4b9c6d
Create Date: 2026-05-12 15:02:35.749050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b765d7520169'
down_revision: Union[str, Sequence[str], None] = '3a0ddb4b9c6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('symbols_total', sa.Integer(), nullable=True),
    sa.Column('symbols_done', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('winning_trades', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('avg_return_pct', sa.Float(), nullable=True),
    sa.Column('median_return_pct', sa.Float(), nullable=True),
    sa.Column('best_trade_pct', sa.Float(), nullable=True),
    sa.Column('worst_trade_pct', sa.Float(), nullable=True),
    sa.Column('max_drawdown_pct', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('total_return_pct', sa.Float(), nullable=True),
    sa.Column('benchmark_return_pct', sa.Float(), nullable=True),
    sa.Column('equity_curve_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('backtest_trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('signal_date', sa.Date(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=False),
    sa.Column('exit_reason', sa.String(), nullable=False),
    sa.Column('signal_score', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=False),
    sa.Column('return_pct', sa.Float(), nullable=False),
    sa.Column('rsi_at_signal', sa.Float(), nullable=True),
    sa.Column('adx_at_signal', sa.Float(), nullable=True),
    sa.Column('ema_signal', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backtest_trades')
    op.drop_table('backtest_runs')
    # ### end Alembic commands ###
