"""add sector snapshots table

Revision ID: bb53787bd712
Revises: 96609b572ba1
Create Date: 2026-05-20 18:45:59.966648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb53787bd712'
down_revision: Union[str, Sequence[str], None] = '96609b572ba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sector_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('avg_rs', sa.Float(), nullable=True),
    sa.Column('avg_momentum_3m', sa.Float(), nullable=True),
    sa.Column('bullish_pct', sa.Float(), nullable=True),
    sa.Column('stock_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'sector')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sector_snapshots')
    # ### end Alembic commands ###
