"""add_fundamental_cache_backoff_fields

Revision ID: bd36d63c5fdf
Revises: 780337900565
Create Date: 2026-05-11 13:55:23.381536

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd36d63c5fdf"
down_revision: Union[str, Sequence[str], None] = "780337900565"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "fundamental_cache", sa.Column("retry_after", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "fundamental_cache", sa.Column("fetch_attempts", sa.Integer(), nullable=True)
    )
    op.add_column(
        "fundamental_cache", sa.Column("last_error", sa.String(), nullable=True)
    )
    op.add_column(
        "fundamental_cache", sa.Column("force_refresh", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fundamental_cache", "force_refresh")
    op.drop_column("fundamental_cache", "last_error")
    op.drop_column("fundamental_cache", "fetch_attempts")
    op.drop_column("fundamental_cache", "retry_after")
    # ### end Alembic commands ###
