"""add dashboard enhancement fields and market_snapshots table

Revision ID: d142dda354d7
Revises: 154fdbdf9867
Create Date: 2026-05-07 16:20:56.778010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd142dda354d7'
down_revision: Union[str, Sequence[str], None] = '154fdbdf9867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_snapshots',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('change_pct', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date', 'symbol')
    )
    op.add_column('pipeline_runs', sa.Column('tier1_count', sa.Integer(), nullable=True))
    op.add_column('pipeline_runs', sa.Column('tier2_count', sa.Integer(), nullable=True))
    op.add_column('technical_signals', sa.Column('close_price', sa.Float(), nullable=True))
    op.add_column('technical_signals', sa.Column('price_change_pct', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('technical_signals', 'price_change_pct')
    op.drop_column('technical_signals', 'close_price')
    op.drop_column('pipeline_runs', 'tier2_count')
    op.drop_column('pipeline_runs', 'tier1_count')
    op.drop_table('market_snapshots')
    # ### end Alembic commands ###
