"""add_fundamental_cache_and_extra_fields

Revision ID: dee1660be5cc
Revises: f7c30a344d0e
Create Date: 2026-05-07 11:28:50.971626

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dee1660be5cc"
down_revision: Union[str, Sequence[str], None] = "f7c30a344d0e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fundamental_cache",
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("profitability_streak_passed", sa.Boolean(), nullable=True),
        sa.Column("de_ratio", sa.Float(), nullable=True),
        sa.Column("de_check_passed", sa.Boolean(), nullable=True),
        sa.Column("pledged_data_missing", sa.Boolean(), nullable=True),
        sa.Column("sector", sa.String(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.Column("cache_version", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("symbol"),
    )
    op.add_column(
        "fundamental_data", sa.Column("pledged_percent", sa.Float(), nullable=True)
    )
    op.add_column(
        "fundamental_data", sa.Column("market_cap", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fundamental_data", "market_cap")
    op.drop_column("fundamental_data", "pledged_percent")
    op.drop_table("fundamental_cache")
    # ### end Alembic commands ###
