"""add_trade_journal_table

Revision ID: ebe325b82d9e
Revises: aaf42b552175
Create Date: 2026-05-24 17:03:45.706157

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ebe325b82d9e"
down_revision: Union[str, Sequence[str], None] = "aaf42b552175"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trade_journal",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("watchlist_id", sa.Integer(), nullable=True),
        sa.Column("signal_date", sa.Date(), nullable=True),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("entry_price", sa.Float(), nullable=False),
        sa.Column("shares", sa.Integer(), nullable=False),
        sa.Column("position_value", sa.Float(), nullable=False),
        sa.Column("stop_loss", sa.Float(), nullable=False),
        sa.Column("target", sa.Float(), nullable=False),
        sa.Column("quality_tier", sa.String(length=1), nullable=True),
        sa.Column("signal_score", sa.Float(), nullable=True),
        sa.Column("exit_date", sa.Date(), nullable=True),
        sa.Column("exit_price", sa.Float(), nullable=True),
        sa.Column("exit_reason", sa.String(), nullable=True),
        sa.Column("pnl", sa.Float(), nullable=True),
        sa.Column("return_pct", sa.Float(), nullable=True),
        sa.Column("holding_days", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["watchlist_id"],
            ["watchlist.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_tj_status", "trade_journal", ["status"], unique=False)
    op.create_index("ix_tj_symbol", "trade_journal", ["symbol"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tj_symbol", table_name="trade_journal")
    op.drop_index("ix_tj_status", table_name="trade_journal")
    op.drop_table("trade_journal")
    # ### end Alembic commands ###
