"""add gross return and cost drag to backtest runs

Revision ID: ece6eaedeaec
Revises: ed7f7c7796f4
Create Date: 2026-05-19 19:42:37.243163

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ece6eaedeaec"
down_revision: Union[str, Sequence[str], None] = "ed7f7c7796f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "backtest_runs", sa.Column("gross_return_pct", sa.Float(), nullable=True)
    )
    op.add_column(
        "backtest_runs", sa.Column("total_cost_drag_pct", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("backtest_runs", "total_cost_drag_pct")
    op.drop_column("backtest_runs", "gross_return_pct")
    # ### end Alembic commands ###
