"""add expectancy and metrics to backtest_runs

Revision ID: ed7f7c7796f4
Revises: cd759c79f225
Create Date: 2026-05-16 11:52:12.380903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed7f7c7796f4'
down_revision: Union[str, Sequence[str], None] = 'cd759c79f225'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backtest_runs', sa.Column('expectancy', sa.Float(), nullable=True))
    op.add_column('backtest_runs', sa.Column('profit_factor', sa.Float(), nullable=True))
    op.add_column('backtest_runs', sa.Column('avg_win_pct', sa.Float(), nullable=True))
    op.add_column('backtest_runs', sa.Column('avg_loss_pct', sa.Float(), nullable=True))
    op.add_column('backtest_runs', sa.Column('exit_breakdown_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtest_runs', 'exit_breakdown_json')
    op.drop_column('backtest_runs', 'avg_loss_pct')
    op.drop_column('backtest_runs', 'avg_win_pct')
    op.drop_column('backtest_runs', 'profit_factor')
    op.drop_column('backtest_runs', 'expectancy')
    # ### end Alembic commands ###
