"""Initial schema

Revision ID: f7c30a344d0e
Revises:
Create Date: 2026-05-06 17:55:06.625378

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f7c30a344d0e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_scores",
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("entry_score", sa.Float(), nullable=True),
        sa.Column("rsi", sa.Float(), nullable=True),
        sa.Column("macd", sa.Float(), nullable=True),
        sa.Column("ema_signal", sa.String(), nullable=True),
        sa.Column("volume_signal", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("date", "symbol"),
    )
    op.create_table(
        "fundamental_data",
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("pe", sa.Float(), nullable=True),
        sa.Column("pb", sa.Float(), nullable=True),
        sa.Column("roe", sa.Float(), nullable=True),
        sa.Column("debt_equity", sa.Float(), nullable=True),
        sa.Column("eps_growth", sa.Float(), nullable=True),
        sa.Column("promoter_holding", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("date", "symbol"),
    )
    op.create_table(
        "pipeline_runs",
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("stocks_fetched", sa.Integer(), nullable=True),
        sa.Column("stocks_scored", sa.Integer(), nullable=True),
        sa.Column("errors", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_table(
        "stocks",
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("sector", sa.String(), nullable=True),
        sa.Column("industry", sa.String(), nullable=True),
        sa.Column("market_cap", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("symbol"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stocks")
    op.drop_table("pipeline_runs")
    op.drop_table("fundamental_data")
    op.drop_table("daily_scores")
    # ### end Alembic commands ###
